AWSTemplateFormatVersion: "2010-09-09"
Description: >
  ECS Cluster, Task Definition, EventBridge Schedule, IAM Roles. Supports dev/prod environments.

Conditions:
  IsDev: !Equals [ !Ref Environment, "dev" ]
  
Parameters:
  Environment:
    Type: String
    Default: "dev"
    AllowedValues:
      - dev
      - prod
    Description: "Deployment environment (dev or prod)"

  ContainerImage:
    Type: String
    Description: "ECR image URI or container image for the ECS task"

  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: "Subnets for ECS task (Fargate launch)"

  SecurityGroups:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: "Security groups for ECS task"

  ScheduleExpression:
    Type: String
    Default: "rate(1 day)"
    Description: "EventBridge schedule expression (cron or rate)"

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "blockbuster-index-${Environment}"

  ECSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/blockbuster-index-${Environment}"
      RetentionInDays: 14

  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "blockbuster-index-ecs-task-execution-role-${Environment}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: "CloudWatchLogsPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/ecs/blockbuster-index-${Environment}:*"

  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "blockbuster-index-ecs-task-role-${Environment}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"

  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "blockbuster-index-task-${Environment}"
      Cpu: "512"
      Memory: "1024"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      TaskRoleArn: !GetAtt ECSTaskRole.Arn
      ContainerDefinitions:
        - Name: blockbuster-index-container
          Image: !Ref ContainerImage
          Cpu: 512
          Memory: 1024
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref ECSLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: "blockbuster-index"
          Environment:
            - Name: NODE_ENV
              Value: !If
                - IsDev
                - "test"
                - "production"
            - Name: OPENAI_API_KEY
              Value: !Sub "{{resolve:secretsmanager:blockbuster-index-openai-${Environment}:SecretString:apiKey}}"

  EventBridgeInvokeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "blockbuster-index-eventbridge-invoke-role-${Environment}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: "AllowRunTask"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecs:RunTask
                Resource:
                  - !Ref ECSTaskDefinition
                  - !GetAtt ECSCluster.Arn
                Condition:
                  StringEquals:
                    ecs:cluster: !Ref ECSCluster

  ScheduledTaskRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "blockbuster-index-scheduled-task-rule-${Environment}"
      ScheduleExpression: !Ref ScheduleExpression
      State: "ENABLED"
      Targets:
        - Arn: !GetAtt ECSCluster.Arn
          Id: "BlockbusterIndexECSTask"
          RoleArn: !GetAtt EventBridgeInvokeRole.Arn
          EcsParameters:
            TaskDefinitionArn: !Ref ECSTaskDefinition
            TaskCount: 1
            LaunchType: FARGATE
            NetworkConfiguration:
              AwsVpcConfiguration:
                AssignPublicIp: ENABLED
                SecurityGroups: !Ref SecurityGroups
                Subnets: !Ref Subnets

Outputs:
  ECSClusterName:
    Description: "ECS Cluster Name"
    Value: !Ref ECSCluster

  ECSClusterArn:
    Description: "ECS Cluster ARN"
    Value: !GetAtt ECSCluster.Arn

  ECSTaskDefinitionArn:
    Description: "ECS Task Definition ARN"
    Value: !Ref ECSTaskDefinition