AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB tables for Blockbuster Index signals.'

Parameters:
  Environment:
    Type: String
    Default: 'dev'
    AllowedValues:
      - dev
      - prod

Resources:
  AmazonJobsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub 'blockbuster-index-amazon-jobs-${Environment}'
      AttributeDefinitions:
        - AttributeName: state
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: state
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: false
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
  CensusSignalsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub blockbuster-index-census-signals-${Environment}
      AttributeDefinitions:
        - AttributeName: state
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: state
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  BroadbandSignalsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub blockbuster-index-broadband-signals-${Environment}
      AttributeDefinitions:
        - AttributeName: state
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
        - AttributeName: dataVersion
          AttributeType: S
      KeySchema:
        - AttributeName: state
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: state-dataVersion-index
          KeySchema:
            - AttributeName: state
              KeyType: HASH
            - AttributeName: dataVersion
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
  AmazonSlidingWindowTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub 'blockbuster-index-amazon-sliding-window-${Environment}'
      AttributeDefinitions:
        - AttributeName: state
          AttributeType: S
        - AttributeName: windowStart
          AttributeType: N
      KeySchema:
        - AttributeName: state
          KeyType: HASH
        - AttributeName: windowStart
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: false
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment

  SignalScoresTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub 'blockbuster-index-signal-scores-${Environment}'
      AttributeDefinitions:
        - AttributeName: signalType
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: signalType
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: false
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment

  BlockbusterIndexTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub 'blockbuster-index-blockbuster-index-${Environment}'
      AttributeDefinitions:
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: timestamp
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: false
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment

  WalmartJobsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub 'blockbuster-index-walmart-jobs-${Environment}'
      AttributeDefinitions:
        - AttributeName: state
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: state
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: false
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment

  WalmartSlidingWindowV2Table:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub 'blockbuster-index-walmart-sliding-window-${Environment}'
      AttributeDefinitions:
        - AttributeName: state
          AttributeType: S
        - AttributeName: windowStart
          AttributeType: N
      KeySchema:
        - AttributeName: state
          KeyType: HASH
        - AttributeName: windowStart
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: false
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment

  BlsProcessedFilesTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub 'blockbuster-index-bls-processed-files-${Environment}'
      AttributeDefinitions:
        - AttributeName: year
          AttributeType: S
      KeySchema:
        - AttributeName: year
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: false
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment

  BlsStateDataTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub 'blockbuster-index-bls-state-data-${Environment}'
      AttributeDefinitions:
        - AttributeName: state_year
          AttributeType: S
        - AttributeName: state
          AttributeType: S
      KeySchema:
        - AttributeName: state_year
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: state-index
          KeySchema:
            - AttributeName: state
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: false
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment

  BlsSignalsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub 'blockbuster-index-bls-signals-${Environment}'
      AttributeDefinitions:
        - AttributeName: state_fips
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: state_fips
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: false
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment

Outputs:
  AmazonJobsTableArn:
    Description: 'ARN of the Amazon Jobs table'
    Value: !GetAtt AmazonJobsTable.Arn
    Export:
      Name: !Sub '${Environment}-BlockbusterAmazonJobsTableArn'
  CensusSignalsTableArn:
    Description: 'ARN of the Census Signals table'
    Value: !GetAtt CensusSignalsTable.Arn
    Export:
      Name: !Sub '${Environment}-BlockbusterCensusSignalsTableArn'
  BroadbandSignalsTableArn:
    Description: 'ARN of the Broadband Signals table'
    Value: !GetAtt BroadbandSignalsTable.Arn
    Export:
      Name: !Sub '${Environment}-BlockbusterBroadbandSignalsTableArn'
  AmazonSlidingWindowTableArn:
    Description: 'ARN of the Amazon Sliding Window table'
    Value: !GetAtt AmazonSlidingWindowTable.Arn
    Export:
      Name: !Sub '${Environment}-BlockbusterAmazonSlidingWindowTableArn'
  SignalScoresTableArn:
    Description: 'ARN of the Signal Scores table'
    Value: !GetAtt SignalScoresTable.Arn
    Export:
      Name: !Sub '${Environment}-BlockbusterSignalScoresTableArn'
  BlockbusterIndexTableArn:
    Description: 'ARN of the Blockbuster Index table'
    Value: !GetAtt BlockbusterIndexTable.Arn
    Export:
      Name: !Sub '${Environment}-BlockbusterBlockbusterIndexTableArn'
  WalmartJobsTableArn:
    Description: 'ARN of the Walmart Jobs table'
    Value: !GetAtt WalmartJobsTable.Arn
    Export:
      Name: !Sub '${Environment}-BlockbusterWalmartJobsTableArn'
  WalmartSlidingWindowTableArn:
    Description: 'ARN of the Walmart Sliding Window table'
    Value: !GetAtt WalmartSlidingWindowV2Table.Arn
    Export:
      Name: !Sub '${Environment}-BlockbusterWalmartSlidingWindowTableArn'
  BlsProcessedFilesTableArn:
    Description: 'ARN of the BLS Processed Files table'
    Value: !GetAtt BlsProcessedFilesTable.Arn
    Export:
      Name: !Sub '${Environment}-BlockbusterBlsProcessedFilesTableArn'
  BlsStateDataTableArn:
    Description: 'ARN of the BLS State Data table'
    Value: !GetAtt BlsStateDataTable.Arn
    Export:
      Name: !Sub '${Environment}-BlockbusterBlsStateDataTableArn'
  BlsSignalsTableArn:
    Description: 'ARN of the BLS Signals table'
    Value: !GetAtt BlsSignalsTable.Arn
    Export:
      Name: !Sub '${Environment}-BlockbusterBlsSignalsTableArn' 