AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS Task Definitions and Scheduled Rules for Blockbuster Index Signals.'

Mappings:
  EnvConfig:
    dev:
      Subnets:
        - subnet-02ce757a
        - subnet-2655df7b
        - subnet-e22085a8
        - subnet-badfdd91
      SecurityGroups:
        - sg-09812900f87093af6
      S3BucketName: 'blockbuster-index-client-dev'
      LogLevel: 'info'
    prod:
      Subnets:
        - subnet-02ce757a
        - subnet-2655df7b
        - subnet-e22085a8
        - subnet-badfdd91
      SecurityGroups:
        - sg-03003b7a95e81b834
      S3BucketName: 'blockbuster-index-client-prod'
      LogLevel: 'warn'

Conditions:
  IsDev: !Equals [!Ref Environment, 'dev']
  IsAmazon: !Equals [!Ref SignalType, 'amazon']
  IsCensus: !Equals [!Ref SignalType, 'census']
  IsBroadband: !Equals [!Ref SignalType, 'broadband']
  IsBlockbusterIndex: !Equals [!Ref SignalType, 'blockbuster-index']
  IsProdAmazon: !And [!Equals [!Ref Environment, 'prod'], !Equals [!Ref SignalType, 'amazon']]
  IsProdCensus: !And [!Equals [!Ref Environment, 'prod'], !Equals [!Ref SignalType, 'census']]
  IsProdBroadband: !And [!Equals [!Ref Environment, 'prod'], !Equals [!Ref SignalType, 'broadband']]
  IsProdBlockbusterIndex: !And [!Equals [!Ref Environment, 'prod'], !Equals [!Ref SignalType, 'blockbuster-index']]

Parameters:
  Environment:
    Type: String
    Default: 'dev'
    AllowedValues:
      - dev
      - prod

  SignalType:
    Type: String
    AllowedValues:
      - amazon
      - census
      - broadband
      - blockbuster-index
    Description: 'Type of signal to deploy task definition for'

  ContainerImage:
    Type: String
    Description: 'ECR image URI or container image for the ECS task'

# --- ECS Task Definitions for Each Signal ---

Resources:
  AmazonECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Condition: IsAmazon
    Properties:
      Family: !Sub 'blockbuster-index-amazon-task-${Environment}'
      Cpu: '512'
      Memory: '2048'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue
        Fn::Sub: '${Environment}-BlockbusterExecutionRoleArn'
      TaskRoleArn: !ImportValue
        Fn::Sub: '${Environment}-BlockbusterTaskRoleArn'
      ContainerDefinitions:
        - Name: blockbuster-index-amazon-container
          Image: !Ref ContainerImage
          Cpu: 512
          Memory: 1024
          Essential: true
          Command: ["node", "dist/index.js"]
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !ImportValue
                Fn::Sub: '${Environment}-BlockbusterAmazonLogGroupName'
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: 'blockbuster-index-amazon'
          Environment:
            - Name: NODE_ENV
              Value: 'production'
            - Name: LOG_LEVEL
              Value: !FindInMap [EnvConfig, !Ref Environment, LogLevel]
            - Name: S3_BUCKET_NAME
              Value: !FindInMap [EnvConfig, !Ref Environment, S3BucketName]
            - Name: AMAZON_DYNAMODB_TABLE_NAME
              Value: !Sub 'blockbuster-index-amazon-jobs-${Environment}'
            - Name: AMAZON_SLIDING_WINDOW_TABLE_NAME
              Value: !Sub 'blockbuster-index-amazon-sliding-window-${Environment}'
            - Name: AWS_REGION
              Value: !Ref AWS::Region
            - Name: CACHE_CONTROL
              Value: 'max-age=300'
            - Name: MAX_RETRIES
              Value: '3'
            - Name: npm_package_version
              Value: '1.0.0'
            - Name: OPENAI_API_KEY
              Value: !Sub '{{resolve:secretsmanager:blockbuster-index-openai-${Environment}:SecretString:apiKey}}'
            - Name: RETRY_DELAY
              Value: '1000'
            - Name: CW_LOG_GROUP
              Value: !ImportValue
                Fn::Sub: '${Environment}-BlockbusterAmazonLogGroupName'
            - Name: CW_LOG_STREAM
              Value: !Sub 'blockbuster-index-mcp-amazon-${Environment}-${AWS::StackName}'

  CensusECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Condition: IsCensus
    Properties:
      Family: !Sub 'blockbuster-index-census-task-${Environment}'
      Cpu: '512'
      Memory: '2048'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue
        Fn::Sub: '${Environment}-BlockbusterExecutionRoleArn'
      TaskRoleArn: !ImportValue
        Fn::Sub: '${Environment}-BlockbusterTaskRoleArn'
      ContainerDefinitions:
        - Name: blockbuster-index-census-container
          Image: !Ref ContainerImage
          Cpu: 512
          Memory: 1024
          Essential: true
          Command: ["node", "dist/index.js"]
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !ImportValue
                Fn::Sub: '${Environment}-BlockbusterCensusLogGroupName'
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: 'blockbuster-index-census'
          Environment:
            - Name: NODE_ENV
              Value: 'production'
            - Name: LOG_LEVEL
              Value: !FindInMap [EnvConfig, !Ref Environment, LogLevel]
            - Name: S3_BUCKET_NAME
              Value: !FindInMap [EnvConfig, !Ref Environment, S3BucketName]
            - Name: CENSUS_DYNAMODB_TABLE_NAME
              Value: !Sub 'blockbuster-index-census-signals-${Environment}'
            - Name: AWS_REGION
              Value: !Ref AWS::Region
            - Name: CACHE_CONTROL
              Value: 'max-age=300'
            - Name: MAX_RETRIES
              Value: '3'
            - Name: npm_package_version
              Value: '1.0.0'
            - Name: OPENAI_API_KEY
              Value: !Sub '{{resolve:secretsmanager:blockbuster-index-openai-${Environment}:SecretString:apiKey}}'
            - Name: RETRY_DELAY
              Value: '1000'
            - Name: CW_LOG_GROUP
              Value: !ImportValue
                Fn::Sub: '${Environment}-BlockbusterCensusLogGroupName'
            - Name: CW_LOG_STREAM
              Value: !Sub 'blockbuster-index-mcp-census-${Environment}-${AWS::StackName}'

  BroadbandECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Condition: IsBroadband
    Properties:
      Family: !Sub 'blockbuster-index-broadband-task-${Environment}'
      Cpu: '512'
      Memory: '2048'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue
        Fn::Sub: '${Environment}-BlockbusterExecutionRoleArn'
      TaskRoleArn: !ImportValue
        Fn::Sub: '${Environment}-BlockbusterTaskRoleArn'
      ContainerDefinitions:
        - Name: blockbuster-index-broadband-container
          Image: !Ref ContainerImage
          Cpu: 512
          Memory: 1024
          Essential: true
          Command: ["node", "dist/index.js"]
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !ImportValue
                Fn::Sub: '${Environment}-BlockbusterBroadbandLogGroupName'
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: 'blockbuster-index-broadband'
          Environment:
            - Name: NODE_ENV
              Value: 'production'
            - Name: LOG_LEVEL
              Value: !FindInMap [EnvConfig, !Ref Environment, LogLevel]
            - Name: S3_BUCKET_NAME
              Value: !FindInMap [EnvConfig, !Ref Environment, S3BucketName]
            - Name: BROADBAND_DYNAMODB_TABLE_NAME
              Value: !Sub 'blockbuster-index-broadband-signals-${Environment}'
            - Name: BROADBAND_S3_BUCKET_NAME
              Value: !Sub 'blockbuster-index-broadband-${Environment}'
            - Name: AWS_REGION
              Value: !Ref AWS::Region
            - Name: CACHE_CONTROL
              Value: 'max-age=300'
            - Name: MAX_RETRIES
              Value: '3'
            - Name: npm_package_version
              Value: '1.0.0'
            - Name: OPENAI_API_KEY
              Value: !Sub '{{resolve:secretsmanager:blockbuster-index-openai-${Environment}:SecretString:apiKey}}'
            - Name: RETRY_DELAY
              Value: '1000'
            - Name: CW_LOG_GROUP
              Value: !ImportValue
                Fn::Sub: '${Environment}-BlockbusterBroadbandLogGroupName'
            - Name: CW_LOG_STREAM
              Value: !Sub 'blockbuster-index-mcp-broadband-${Environment}-${AWS::StackName}'

  BlockbusterIndexECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Condition: IsBlockbusterIndex
    Properties:
      Family: !Sub 'blockbuster-index-blockbuster-index-task-${Environment}'
      Cpu: '512'
      Memory: '2048'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue
        Fn::Sub: '${Environment}-BlockbusterExecutionRoleArn'
      TaskRoleArn: !ImportValue
        Fn::Sub: '${Environment}-BlockbusterTaskRoleArn'
      ContainerDefinitions:
        - Name: blockbuster-index-blockbuster-index-container
          Image: !Ref ContainerImage
          Cpu: 512
          Memory: 1024
          Essential: true
          Command: ["node", "dist/index.js"]
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !ImportValue
                Fn::Sub: '${Environment}-BlockbusterBlockbusterIndexLogGroupName'
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: 'blockbuster-index-blockbuster-index'
          Environment:
            - Name: NODE_ENV
              Value: 'production'
            - Name: LOG_LEVEL
              Value: !FindInMap [EnvConfig, !Ref Environment, LogLevel]
            - Name: S3_BUCKET_NAME
              Value: !FindInMap [EnvConfig, !Ref Environment, S3BucketName]
            - Name: AWS_REGION
              Value: !Ref AWS::Region
            - Name: CACHE_CONTROL
              Value: 'max-age=300'
            - Name: MAX_RETRIES
              Value: '3'
            - Name: npm_package_version
              Value: '1.0.0'
            - Name: OPENAI_API_KEY
              Value: !Sub '{{resolve:secretsmanager:blockbuster-index-openai-${Environment}:SecretString:apiKey}}'
            - Name: RETRY_DELAY
              Value: '1000'
            - Name: CW_LOG_GROUP
              Value: !ImportValue
                Fn::Sub: '${Environment}-BlockbusterBlockbusterIndexLogGroupName'
            - Name: CW_LOG_STREAM
              Value: !Sub 'blockbuster-index-mcp-blockbuster-index-${Environment}-${AWS::StackName}'

  # --- Scheduled EventBridge Rules for Each Task ---

  AmazonScheduledTaskRule:
    Type: AWS::Events::Rule
    Condition: IsProdAmazon
    Properties:
      Name: !Sub 'blockbuster-index-amazon-scheduled-task-rule-${Environment}'
      ScheduleExpression: 'cron(0 10 * * ? *)' # 10AM UTC
      State: ENABLED
      Targets:
        - Arn: !ImportValue
            Fn::Sub: '${Environment}-BlockbusterECSClusterArn'
          Id: 'BlockbusterIndexAmazonECSTask'
          RoleArn: !ImportValue
            Fn::Sub: '${Environment}-BlockbusterEventBridgeInvokeRoleArn'
          EcsParameters:
            TaskDefinitionArn: !Ref AmazonECSTaskDefinition
            TaskCount: 1
            LaunchType: FARGATE
            NetworkConfiguration:
              AwsVpcConfiguration:
                AssignPublicIp: ENABLED
                SecurityGroups: !FindInMap [EnvConfig, !Ref Environment, SecurityGroups]
                Subnets: !FindInMap [EnvConfig, !Ref Environment, Subnets]

  CensusScheduledTaskRule:
    Type: AWS::Events::Rule
    Condition: IsProdCensus
    Properties:
      Name: !Sub 'blockbuster-index-census-scheduled-task-rule-${Environment}'
      ScheduleExpression: 'cron(0 10 * * ? *)' # 10AM UTC
      State: ENABLED
      Targets:
        - Arn: !ImportValue
            Fn::Sub: '${Environment}-BlockbusterECSClusterArn'
          Id: 'BlockbusterIndexCensusECSTask'
          RoleArn: !ImportValue
            Fn::Sub: '${Environment}-BlockbusterEventBridgeInvokeRoleArn'
          EcsParameters:
            TaskDefinitionArn: !Ref CensusECSTaskDefinition
            TaskCount: 1
            LaunchType: FARGATE
            NetworkConfiguration:
              AwsVpcConfiguration:
                AssignPublicIp: ENABLED
                SecurityGroups: !FindInMap [EnvConfig, !Ref Environment, SecurityGroups]
                Subnets: !FindInMap [EnvConfig, !Ref Environment, Subnets]

  BroadbandScheduledTaskRule:
    Type: AWS::Events::Rule
    Condition: IsProdBroadband
    Properties:
      Name: !Sub 'blockbuster-index-broadband-scheduled-task-rule-${Environment}'
      ScheduleExpression: 'cron(0 10 * * ? *)' # 10AM UTC
      State: ENABLED
      Targets:
        - Arn: !ImportValue
            Fn::Sub: '${Environment}-BlockbusterECSClusterArn'
          Id: 'BlockbusterIndexBroadbandECSTask'
          RoleArn: !ImportValue
            Fn::Sub: '${Environment}-BlockbusterEventBridgeInvokeRoleArn'
          EcsParameters:
            TaskDefinitionArn: !Ref BroadbandECSTaskDefinition
            TaskCount: 1
            LaunchType: FARGATE
            NetworkConfiguration:
              AwsVpcConfiguration:
                AssignPublicIp: ENABLED
                SecurityGroups: !FindInMap [EnvConfig, !Ref Environment, SecurityGroups]
                Subnets: !FindInMap [EnvConfig, !Ref Environment, Subnets]

  BlockbusterIndexScheduledTaskRule:
    Type: AWS::Events::Rule
    Condition: IsProdBlockbusterIndex
    Properties:
      Name: !Sub 'blockbuster-index-blockbuster-index-scheduled-task-rule-${Environment}'
      ScheduleExpression: 'cron(0 22 * * ? *)' # 10PM UTC (12 hours after signals)
      State: ENABLED
      Targets:
        - Arn: !ImportValue
            Fn::Sub: '${Environment}-BlockbusterECSClusterArn'
          Id: 'BlockbusterIndexBlockbusterIndexECSTask'
          RoleArn: !ImportValue
            Fn::Sub: '${Environment}-BlockbusterEventBridgeInvokeRoleArn'
          EcsParameters:
            TaskDefinitionArn: !Ref BlockbusterIndexECSTaskDefinition
            TaskCount: 1
            LaunchType: FARGATE
            NetworkConfiguration:
              AwsVpcConfiguration:
                AssignPublicIp: ENABLED
                SecurityGroups: !FindInMap [EnvConfig, !Ref Environment, SecurityGroups]
                Subnets: !FindInMap [EnvConfig, !Ref Environment, Subnets]

# --- Outputs ---

Outputs:
  AmazonECSTaskDefinitionArn:
    Description: 'Amazon ECS Task Definition ARN'
    Condition: IsAmazon
    Value: !Ref AmazonECSTaskDefinition
  CensusECSTaskDefinitionArn:
    Description: 'Census ECS Task Definition ARN'
    Condition: IsCensus
    Value: !Ref CensusECSTaskDefinition
  BroadbandECSTaskDefinitionArn:
    Description: 'Broadband ECS Task Definition ARN'
    Condition: IsBroadband
    Value: !Ref BroadbandECSTaskDefinition
  BlockbusterIndexECSTaskDefinitionArn:
    Description: 'Blockbuster Index ECS Task Definition ARN'
    Condition: IsBlockbusterIndex
    Value: !Ref BlockbusterIndexECSTaskDefinition
  S3BucketName:
    Description: 'S3 Bucket Name for data storage'
    Value: !FindInMap [EnvConfig, !Ref Environment, S3BucketName]
