AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB tables for Blockbuster Index signals.'

Parameters:
  Environment:
    Type: String
    Default: 'dev'
    AllowedValues:
      - dev
      - prod

Resources:
  AmazonJobsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub 'blockbuster-index-amazon-jobs-${Environment}'
      AttributeDefinitions:
        - AttributeName: state
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: state
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: false
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
  CensusSignalsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub blockbuster-index-census-signals-${Environment}
      AttributeDefinitions:
        - AttributeName: state
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: state
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

Outputs:
  AmazonJobsTableName:
    Description: 'DynamoDB Table Name for Amazon Job Scraping Data'
    Value: !Ref AmazonJobsTable
    Export:
      Name: !Sub '${Environment}-BlockbusterAmazonJobsTableName'
  AmazonJobsTableArn:
    Description: 'DynamoDB Table ARN for Amazon Job Scraping Data'
    Value: !GetAtt AmazonJobsTable.Arn
    Export:
      Name: !Sub '${Environment}-BlockbusterAmazonJobsTableArn'
  CensusSignalsTableName:
    Description: 'Census Signals Table Name'
    Value: !Ref CensusSignalsTable
  CensusSignalsTableArn:
    Description: 'Census Signals Table ARN'
    Value: !GetAtt CensusSignalsTable.Arn 