name: Rollback

on:
  workflow_dispatch:
    inputs:
      signal_type:
        description: 'Choose signal type to rollback'
        required: true
        type: choice
        options:
          - amazon
          - census
          - broadband
          - blockbuster-index
      container_image_uri:
        description: 'Container image URI to rollback to (e.g., 123456789012.dkr.ecr.us-west-2.amazonaws.com/blockbuster-index-dev:amazon-abcdef)'
        required: true
        type: string
      environment:
        description: 'Choose environment (dev/prod)'
        required: true
        type: choice
        options:
          - dev
          - prod

jobs:
  rollback-ecs-task:
    name: Rollback ECS Fargate Task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Deploy CloudFormation Stack with Rollback Image
        run: |
          aws cloudformation deploy \
            --stack-name blockbuster-index-${{ github.event.inputs.signal_type }}-task-stack-${{ github.event.inputs.environment }} \
            --template-file cloudformation/blockbuster-index-task-definition.yaml \
            --parameter-overrides ContainerImage=${{ github.event.inputs.container_image_uri }} Environment=${{ github.event.inputs.environment }} SignalType=${{ github.event.inputs.signal_type }} \
            --capabilities CAPABILITY_NAMED_IAM \
            --region us-west-2
